name: Build and project #Workflow
on: [push, workflow_dispatch] # Event that triggers the workflow
jobs: #Workflow has job(s)
  test: # Job 1
    runs-on: ubuntu-latest
    steps: #Job has steps
      - name: Checkout code
        uses: actions/checkout@v3 #action
      - name: Install Node.js
        uses: actions/setup-node@v3
        with: #configuration for action
          node-version: 18
      - name: Install dependencies
        run: npm install #simple command, so no need for action.
      - name: Run tests
        run: npm test
  deploy: # Job 2
    runs-on: ubuntu-latest
    needs: test # Job 2 depends on Job 1, will only run if and after Job 1 is successful - Sequential. By default, jobs run in parallel.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy to server
        run: echo "Deploying to server..."
